name: Translate locales json
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "public/locales/en/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Paths filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
            changed:
              - 'public/locales/en/*'

      - name: Translate files
        run: |
          for file in ${{ fromJson(steps.filter.outputs.changed_files) }}
          do
            echo "Translating $file"
            lyqht/deepl-translate-github-action@v2.1.0
            with:
              target_languages: es, zh, pt
              input_file_path: $file
              output_file_name_pattern: public/locales/{language}/${file##*/}
              deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
          done
        if: steps.filter.outputs.changed == 'true'
      - name: Prettify JSON
        run: |
          for file in $(echo ${{ steps.changes.outputs.json_files }})
          do
            jq . $file > temp.json && mv temp.json $file
          done
        if: steps.changes.outputs.json == 'true'
