name: Translate locales json
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "public/locales/en/*"

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Paths filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
            changed:
              - 'public/locales/en/*'

      - name: Set matrix for translation
        id: set-matrix
        run: echo "::set-output name=matrix::{\"file\":${{ steps.filter.outputs.changed_files }}}"

  build:
    needs: prepare_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare_matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Translate files
        uses: lyqht/deepl-translate-github-action@v2.1.0
        with:
          target_languages: es, zh, pt
          input_file_path: ${{ matrix.file }}
          output_file_name_pattern: public/locales/{language}/${{ matrix.file }}
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
